[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "echo 'No build command needed for static site'"

[context.deploy-preview]
  command = "echo 'No build command needed for static site'"
